//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiuBa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostImg
    {
        public int PostImgId { get; set; }
        public string PostImgImages { get; set; }
        public Nullable<int> PostId { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
